id: 'https://superface.ai/profiles/email/SendEmail'
title: 'Send Email Profile'
description: 'Basic profile for sending emails'

usecase SendEmail {
  title: 'Send Email'
  description: 'Send plain text email'
  type: 'unsafe'
  errors: [ SomeBusinessError ]

  input {
    'Email address to send email to'
    to: string

    'Email address to send email from'
    from: string

    'Subject of the email'
    subject: string

    'Plain text content of the body'
    body: string
  }

  result {
    'Id of the message sent' 
    messageId: string
  }
}

model SomeBusinessError {
  title: string
}

model Foo {
  bar: string
  addresses: [Location]
}

model Location {
  street: string
  city: string
}
