# Profile of the map
profile: 'https://superface.ai/profiles/email/SendEmail'

# Provider being mapped
provider: 'https://superface.ai/orgs/sendgrid'


map SendEmail {
  http {
    method: 'post'
    url: 'https://api.sendgrid.com/v3/mail/send'

    security { 
      scheme: bearer
    }

    request application/json body {
      personalizations[0].to[0].email: input.to
      personalizations[0].subject: input.subject
      from.email: input.from
      content[0].type: 'text/plain'
      content[0].value': input.subject
    }

    response 200 */* headers {
      result.messageId: 'X-Message-Id'
    }
  }
}
