this is a statement: 7
this is a {
 nested: "value"
}

this {
  is {
    a {
      multi {
        nested {
          array: ["of", "many", "values", false, 7]
        }
      }
    }
  }
}

multiple {
  value: "a"
  value2: "b"
}


usecase SendEmail {
  parameters {
    to {
      type: "array"
      description: "Email address to send email to"
      
      items {
        type: "string"
      }
    }
    
    subject {
      type: "string"
      description: "Subject of the email"
    }
  }
  
  errors RateLimit {
    ref: "#/models/RateLimitError"
  }
  
  examples: [
    { parameters: "", response: "" }
    { parameters: "", response: "" }
  ]
}

models {
  RateLimitError {
    description: ""
    
    limit {
      type: "number"
    }
  }
}
