
profile: "https://superface.ai/profiles/GetWeather"


map GetWeather http {
  step {
    run: Wrapper
    result {
      @temperature: x 
    }
}

operation Wrapper {
  step: 
    run: GetWeather
    
    parameters {
      input: 42
    }

    result {
      x: temperature
    }

}

operation Compute {
  step: 
    run { 
      answer: "js`${inputValue} + 1`"
    }
}

operation VolejCompute {
  step:
    run: Compute
    parameters {
      inputValue: 42
    }
    result {
      xx: answer
    }
}

operation GetWeather http {
  method: GET
  url: https://api.weather.com/forecast

  response 200 application/json en-Us body {
    temperature: jq`.temp`
    city: jq`.location.city`
    unit: 'F'
  }
}