model X [
  enum {
    A
    B
  }
]

model A {} 

model Y { name } | { email }

field foobar A! | B

model H { 
  name
  address 
}


model H { name string, address number }
model H { name: NameModel address: AddressModel }

model UWE {
  f1 enum { a b }
  f2 string 
  f3 {
    f3a
    f3b
  }
  f4 { f4a, f4b boolean }     # Ok, but without comma -> error
  f5 f6 f7                    # -> error
  f8, f9, f10                 # -> OK
  f11 string f12              # -> error
  f13 string, f14             # -> OK
}

# Not supported:
model UWE {
  f1: enum { a b }
  f2: string 
  f3: {
    f3a
    f3b
  }
  f4: { f4a, f4b: boolean }    # -> Ok, event without comma, note I do not like the `f4: {}` 
  f5 f6 f7                     # -> OK
  f8, f9, f10                  # -> OK
  f11: string f12              # -> OK
  f13: string, f14             # -> OK
}
