"""
Superface Map

Definition of use-cases for the superface map store. See http://superface.ai for more details.
"""

profile = "https://superface.ai/profiles/superface/Map"

#
# Use cases
#

"""
Get Map

Retrieves information about a map based on its id
"""
usecase GetMap safe {
  input {
    mapId
  }
  
  result Map
}

"""
Create Map

Creates new map from the map source and assigns a store Map ID to it
"""
usecase CreateMap unsafe {
  input {
    source
  }
  
  result Map
}

"""
Udpate Map

Updates map source based on its URL
"""
usecase UpdateMap idempotent {
  input {
    mapId
    source
  }

  result Map
}

"""
Delete Map

Deletes map based on its URL
"""
usecase DeleteMap unsafe {
  input {
    mapId
  }
}

"""
Retrieve Map Source

Fetches the map source as stored
"""
usecase GetMapSource safe {
  input {
    mapId
  }

  # "Source code of the map"
  result string
}

#
# Reusable Models
#
model Map {
  mapId
  source
  sourceUrl
}

#
# Reusable Fields
#

"""
Map ID

Id of the map
"""
field mapId string

"""
Source

Source code of the map
"""
field source string

"""
Source URL

URL of the map source. Can be directly queried using the HTTP GET method
"""
field sourceUrl string
