operation foo {
  return {
    answer = 42
    hash = { a: 1, b: 2 }
  }
}

operation fooWithArgs {
  return if (args.success) {
    answer = 42
  }

  fail if (!args.succes) {
    message = "I am supposed to fail"
  }
}

operation bar {
  call fooWithArgs(success = `Muj string ${someVar}`, neco = 4+2 ) {
    return if (!error) {
      finalAnswer = "The final answer is " + data.answer
    }

    fail if (error) {
      finalAnswer = "There was an error " + error.message
    }
  }

}

operation countArray {
  count = 0
  
  set forEach(args.array) {
    count = count + 1
  }

  return {
    answer = "This is the count " + count
  }
}
