profile = "http://supermodel.io/superface/CRM/Customers"
provider = "http://superface.ai/directory/Pipedrive"

map RetrieveCustomers {
  # Local variables
  filterId = null

  # Step 1
  call FindFilter(filterName = "my-superface-map-filter") if(input.since) {
    set if (!error) {
      filterId = return.filterId
    }
  }

  # Step 2
  call CreateFilter(filterId = filterId) if(input.since && !filterId) {
    set if (!error) {
      filterId = return.filterId
    }
  }

  # Step 3
  call RetrieveOrganizations(filterId = filterId) {
    map result if (!error && data) {
      customers = data.customers
    }
  }

  # Step 4
  call Cleanup() if(filterId) {
    # ... 
  }
}

operation FindFilter {

}

operation CreateFilter {

}

operation RetrieveOrganizations {

}





