map GetGitHubGists {
  http GET "/gists" {
    request headers {
      accept = "application/vnd.github.v3+json"
    }

    response 200 "application/json" {
      map.result.numberOfResults = body.length()
      map.result.auhtors = ProcessAuthors(body)
    }

    response 500 {
      map.error = "No gists for you"
    }

  }
}

operation ProcessAuthors {
  authors = args.authors.map((gist) => return gist.owner.login)
  return authors
}

operation ComplexObject {
  return {
    a = 1
    b.c = 2
    d.e.f = 42
  }
}









#
# Slang
#
some thing {
  a = 4
}

some {
  thing {
    a = 4
  }
}

some {
  thing.a = 4 
}







#
# GraphQL
#

# https://gist.github.com/jamesluberda/d73376298e22e3fc4abbca590b97d5e0
map GetGitHubGistsGQL {
  gql """
query { 
  viewer { 
    gists (first: 100, orderBy: {field: CREATED_AT, direction: DESC} ) {
      edges {
        node {
          createdAt
          description
          name
          pushedAt
          stargazers (first: 100) {
            totalCount
            edges {
              node {
                id
              }
            }
          }
          updatedAt
        }
      }
    }
  }
}
""" 
  {
    map result {
      
    }
  }

}