#
# Map for profile
#
profile = 'http://supermodel.io/superface/telco/SendSMS'

#
# Provider details
#
[provider]
id = 'http://superface.ai/directory/twilio'

#
# Affordance map
#
[map.SendMessage.http]
method = 'GET'
href = '/2010-04-01/Accounts/{AccountSID}/Messages.json'

  [map.SendMessage.http.hrefVariables.AccountSID]
  source = 'security/basic.user'

  [map.SendMessage.http.request.headers]
  some-http-header = 42

  [map.SendMessage.http.request.'application/x-www-form-urlencoded'.body]
  # values are using jq syntax - https://stedolan.github.io/jq, https://jqplay.org/#
  # alternativelly we can consider JSON Pointer https://tools.ietf.org/html/rfc6901

  from = '.From'      # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/from
  to = '.To'          # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/to
  message = '.Body'   # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/message

  [map.SendMessage.http.response.200.'application/json'.body]
  # jq syntax
  to = '.to'          # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/rt/to
  id = '.sid'         # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/rt/sid
