"""
Send Message

Send single conversation message.
"""

profile = "http://superface.ai/profile/conversation/SendMessage"

"Send Message

Send single conversation message"
usecase SendMessage unsafe {
  input {
    "To
      recepient of the message"
    to

    "From
      sender of the message"    
    from
    
    channel

    "Text 
      the text of the message"
    text
  }

  result {
    messageId
  }

  async result {
    messageId
    deliveryStatus
  }

  error {
    problem
    detail
    instance
  }
}

"Message Status

  Retrieve status of a sent message"
usecase RetrieveMessageStatus safe {
  input {
    messageId
  }

  result {
    deliveryStatus
  }

  async result A
}

"Identifier of Message
  The identifier is channel-specific and not unique. It should be treated as an opaque value and only used in subsequent calls"
field messageId string

"Delivery Status of Message
  Status of a sent message. Harmonized across different channels."
field deliveryStatus enum {
  accepted
  delivered
  seen
}

"Channel
  Over-the-air channel for the communication"
field channel enum {
  sms
  whatsapp
  apple_business_chat
  facebook_messenger
}
