profile = "https://superface.ai/profile/manufacturing/CompletionStatus"
provider = "http://superface.ai/directory/demo/CompletionProvider1"

map CompletionStatus {
  http GET "/task-status" {
    request query {
      msn = input.MSN
    }
    
    response 200 "application/json" {
      map result {
        status = body.status
        estimatedCompletion = body.date
      }
    }
  }
}
