profile = "https://superface.ai/profile/manufacturing/CompletionStatus""
provider = "http://superface.ai/directory/demo/CompletionProvider2"

map CompletionStatus {
  http POST "/progress" {
    request "application/json" body {
      serialNumber = input.MSN
    }
    
    response 200 "application/json" {
      map result {
        status = body.currentStatus
        estimatedCompletion = body.estCompletionDate
      }
    }
  }
}
