[usecase.GetWeather]
title = "Get Weather"
description = "Lorem Ipsum"
type = "safe"

  # Parameters
  [usecase.GetWeather.parameters]
  location = "string"

  # Response
  [usecase.GetWeather.response]
  temperature = "string" 
  city = "string" 
  unit = "string"

  errors = ["LocationNotFound"] 

# Reusable model
[model.Location]
city = "string"

  [model.Location.country]
  description = "ISO country code of the location"
  type = "string"

[error.LocationNotFound]
title = "string"

# ------------- Mapping 

profile = "https://superface.ai/profiles/GetWeather"

[map.GetWeather.http]
method = "GET"
url = "http://api.weather.com/"

  [map.GetWeather.http.response.200."application/json".body]
  temperature = ".temp"
  city = ".location.city"
  unit = "F"