#
# Profile
#

# Get Weather
usecase GetWeather {
  title: Get Weather
  description: Lorem Ipsum
  type: safe
  errors: [ LocationNotFound ]

  parameters location {
    type: string
  }

  result {
    temperature { type: string }
    city { type: string }
    unit {
      type: string
      enum: [celsius, farenheit]
    }
  }
}

model Location {
  city { type: string }
  country { 
    description: ISO country code of the location
    type: string
  }
}

error LocationNotFound {
  title: string
}

# ------------- Mapping 

profile: "https://superface.ai/profiles/GetWeather"

map GetWeather http {
  method: GET
  url: https://api.weather.com/forecast

  response 200 application/json body {
    temperature: jq`.temp`
    city: jq`.location.city`
    unit: 'F'
  }
}
