#
# Profile
#

# Get Weather
[usecase.GetWeather]
  title = 'Get Weather'
  description = 'Lorem Ipsum'
  type = 'safe'
  errors = ['LocationNotFound']
  
  # Parameters
  [usecase.GetWeather.parameters]
    [usecase.GetWeather.parameters.location]
    type = 'string'
  
  # Response
  [usecase.GetWeather.results]
    [usecase.GetWeather.result.temperature]
    type = 'string'

    [usecase.GetWeather.result.unit]
    type = 'string'

    [usecase.GetWeather.result.city]
    type = 'string'

# Reusable models
[models.Location.city]
type = 'string'
  
  [models.Location.city.country]
  description = 'ISO country code of the location'
  type = 'string'


[error.LocationNotFound.title]
type = 'string'

# ------------- Mapping 

profile = "https://superface.ai/profiles/GetWeather"

[map.GetWeather.http]
method = 'GET'
url = 'https://api.weather.com/forecast'

  [map.GetWeather.http.200.'application/json'.body]
  'result.temperature' = '.temp'
  'result.location.city' = '.location.city'
  'result.unit' = 'F'
