true = "push"

[jobs]

  [jobs.one]
  runs-on = "ubuntu-16.04"

    [[jobs.one.steps]]
    name = "Dump GitHub context"
    run = "echo \"$GITHUB_CONTEXT\""

      [jobs.one.steps.env]
      GITHUB_CONTEXT = "${{ toJson(github) }}"

    [[jobs.one.steps]]
    name = "Dump job context"
    run = "echo \"$JOB_CONTEXT\""

      [jobs.one.steps.env]
      JOB_CONTEXT = "${{ toJson(job) }}"

    [[jobs.one.steps]]
    name = "Dump steps context"
    run = "echo \"$STEPS_CONTEXT\""

      [jobs.one.steps.env]
      STEPS_CONTEXT = "${{ toJson(steps) }}"

    [[jobs.one.steps]]
    name = "Dump runner context"
    run = "echo \"$RUNNER_CONTEXT\""

      [jobs.one.steps.env]
      RUNNER_CONTEXT = "${{ toJson(runner) }}"

    [[jobs.one.steps]]
    name = "Dump strategy context"
    run = "echo \"$STRATEGY_CONTEXT\""

      [jobs.one.steps.env]
      STRATEGY_CONTEXT = "${{ toJson(strategy) }}"

    [[jobs.one.steps]]
    name = "Dump matrix context"
    run = "echo \"$MATRIX_CONTEXT\""

      [jobs.one.steps.env]
      MATRIX_CONTEXT = "${{ toJson(matrix) }}"