id = 'https://superface.ai/profiles/email/SendEmail'
schema = 'http://superschema.org/draft-01/schema#'

title = 'Send Email Profile'
description = 'Basic profile for sending emails'

[usecase.SendEmail]
title = 'Send Email'
description = 'Send plain text email'
type = 'unsafe'                                                                 # if omitted default: "unsafe"

  [usecase.SendEmail.parameters.to]
  description = 'Email address to send email to'
  type = 'array'                                                               # if omitted default: "any"
  
  [usecase.SendEmail.parameters.to.items]
  type = 'string'

  [usecase.SendEmail.parameters.from]
  description = 'Email address to send email from'
  type = 'string'

  [usecase.SendEmail.parameters.subject]
  description = 'Subject of the email'
  type = 'string'

  [usecase.SendEmail.parameters.body]
  description = 'Plain text content of the body'
  type = 'string'

  [usecase.SendEmail.response.messageId]
  description = 'Id of the message sent'

  [usecase.SendEmail.errors.RececpientQuotaExceeded]                            # -> https://superface.ai/profiles/email/SendEmail#/usecase/SendEmail/errors/RececpientQuotaExceeded
  description = ''
  # title = 'Lorem'                                                             # <- A short, human-readable summary of the problem type.
  # detail = 'Lorem Ipsum'                                                      # <- A human-readable explanation specific to this occurrence of the problem.
  # instance = ''                                                               # <- Reference-id: For http -> URL of the request including
  # fullErrorResponse                                                           # <- As came from fetch()

  [usecase.SendEmail.errors.RececpientQuotaExceeded.quota]
  description = ''
  type = 'number'
  
  [usecase.SendEmail.errors.RececpientQuotaExceeded.actualNumberOfRecepients]
  description = ''
  type = 'number'

  [usecase.SendEmail.errors.RateLimit]
  '$ref' = '#/models/RateLimitError'

  [usecase.SendEmail.errors.RateLimitGlobal]
  '$ref' = 'https://superface.ai/profiles/errors/RateLimit@1.0.1'               # FORBIDEN

  # For later 
  [[usecase.SendEmail.examples]]
  parameters = '''
  {}
  '''
  response = '''
  {}
  '''
  
  [[usecase.SendEmail.examples]]
  parameters = '''
  {}
  '''
  response = '''
  {}
  '''  

#
# Models
#
[models.RateLimitError]
description = ''

[models.RateLimitError.limit]
description = ''

