profile = 'https://superface.ai/profiles/email/SendEmail'

[provider]
id = 'http://superface.ai/directory/SendGrid'                                   # https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

[map.SendEmail.http]
method = 'POST'
url = 'https://api.sendgrid.com/v3/mail/send'
 
  [map.SendEmail.http.security]
  type = 'bearer'   # http header authorization: bearer

  # [map.SendEmail.http.request.headers]
  # authorization = 'bearer ${security.bearertoken}'
  
  [map.SendEmail.http.request.'application/json'.body]
  # '.personalizations[].to[].email' = '${ parameters.to }'
  '.personalizations[0].to[].email' = '${ @parameters.to.email }'
  '.personalizations[0].to[].name' = '${ @parameters.to.name }'
  # '.personalizations[0].to[0].email2' = '${ @https://superface.ai/profiles/email/SendEmail#/functions/SendEmail/parameters/to }'    <- not supported
  '.personalizations[0].subject' = '${ toLowerCase(@parameters.subject) }'
  '.personalizations[0].subject2' = 'Message about ${ @parameters.subject }'
  '.from.email' = '@parameters.from'
  '.content[0].type' = 'text/plain'
  '.content[0].value' = '@parameters.body'


  [map.SendEmail.http.response.200.'*/*'.headers]
  '@response/messageId' = 'X-Message-Id'

  [map.SendEmail.http.response.200.'application/json'.body]
  '@response/neco' = 42
  