profile = 'https://superface.ai/profiles/email/SendEmail'

[provider]
id = 'http://superface.ai/directory/SendGrid'                                   # https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

[map.SendEmail.http]
method = 'POST'
url = 'https://api.sendgrid.com/v3/mail/send'

  [map.SendEmail.http.security]
  type = 'bearer'

  [map.SendEmail.http.request.'application/json'.body]
  '.personalizations[0].to[0].email' = '@parameters/to'
  '.personalizations[0].subject' = '@parameters/subject'
  '.from.email' = '@parameters/from'
  '.content[0].type' = 'text/plain'
  '.content[0].value' = '@parameters/body'

  [map.SendEmail.http.response.202.'*/*'.headers]
  '@response/messageId' = 'X-Message-Id'
