"""
Send Email Profile

Basic profile for sending emails
"""
schema SendEmail @profile(id: "https://superface.ai/profiles/email/SendEmail")
{
  mutation: SendEmail
}


"""
Send Email

Send plain text email
"""
mutation SendEmail(parameters: SendEmailInput) : EmailResult 
  @unsafe
  @errors(models: [RecepientQuotaExceeded, RateLimit])

input SendEmailInput {
  "Email address to send email to"
  to: [String!]!
  
  "Email address to send email from"
  from: String!
  
  "Subject of the email"
  subject: String

  "Subject of the email"
  body: String
}

type EmailResult {
  "Id of the message sent"
  id: String
}

type RecepientQuotaExceeded {
  quota: Number
  actualNumberOfRecepients: Number
}

type RateLimit {
  # ...
}



# Sources
#
# https://graphql.org/learn/schema/
# https://raw.githubusercontent.com/sogko/graphql-shorthand-notation-cheat-sheet/master/graphql-shorthand-notation-cheat-sheet.png
# https://github.com/APIs-guru/graphql-faker
