# super language (slang) examples

foo bar some thing {
  a: 42
}

# Equivalent to lines 3-5
foo bar some {
  thing {
    a: 42
  }
}

# Equivalent to all previous
foo bar {
  some {
    thing {
      a: 42
    }
  }
}

# Equivalent to all previous
foo { 
  bar {
    some {
      thing {
        a: 42
      }
    }
  }
}
