'''
Superface Map
'''
profile: https://superface.ai/profiles/superface/Map

'''
Get Map

Retrieves a map based on its URL (id)
'''
usecase GetMap @safe {
  input {
    mapUrl
  }
  
  result {
    mapUrl
    source
  }
}


'''
Create Map

Creates new map from map source and assigns a URL to it
'''
usecase CreateMap @unsafe {
  input {
    'Map source code'
    source
  }
  
  result {
    'URL of the mapping'
    mapUrl
  }
}

'''
Udpate Map

Updates map source based on its URL
'''
usecase UpdateMap @idempotent {
  input {
    mapUrl
    source
  }

  result {
    mapUrl
  }
}

'''
Delete Map

Deletes map based on its URL
'''
usecase DeleteMap @unsafe {
  input {
    mapUrl
  }
}

'URL of a map'
field mapUrl: String

'Source code of a map'
field source: String
