'''
Autonomous Service Registry

Set of usecases provided by the autonomous service registry.
'''

profile: https://superface.ai/profiles/superface/registry

#
# Use cases
#

'''
Retrieve Service

Retrieve a specific service by its registry id (URL)
'''
usecase RetrieveOneService @safe {
  input {
    registryId
  }

  result: Service
}


'''
Find Service

Find services matching to a profile id
'''
usecase FindServicesByProfile @safe {
  input {
    profileId
  }

  result {
    matches: [Service]
  }
}

'''
Register New Service

Registers a new service in the registry.
If a service with given serviceUrl and profileId is already registered, an error
 is returned.
'''
usecase RegisterService @unsafe {
  input {
    profileId
    serviceUrl
    mappingUrl
  }

  result: Service
}

'''
Unregister Service

Unregister service for a profile id 
'''
usecase UnregisterService @unsafe {
  input {
    profileId
    serviceUrl
  }
}

'''
Update Service

Update service registry entry
'''
usecase UpdateRegistration @idempotent {
  input {
    profileId
    serviceUrl
    mappingUrl
  }

  return: Service  
}

'''
Bind 

Binds caller to a service. Notify the registry the intention to connect with and
 use another service.
'''
usecase Bind {
  input {
    serviceUrl
    profileId

    'Identifier of consuming service or application'
    sourceId
  }

  result {
    # To be decided ...
    grantId
    bindToken
  }
}


#
# Reusable Models
#

'''
Service

Model of a service in the registry
'''
model Service {
  registryId
  serviceUrl
  mappingUrl
  profileId
}

#
# Reusable Fields
#

'''
Profile Id

Reusable profile id property. Identifier of a semantic profile. Link (URL) to a 
profile in the profile service.
'''
field profileId: String
