#
# Map for profile
#
profile = 'http://supermodel.io/superface/WeatherAlerts'

#
# Provider details
#
[provider]
id = 'http://superface.ai/directory/ballistic-sombrero'

#
# Affordance map
#
[map.RetrieveAlerts.http]     # -> http://supermodel.io/superface/WeatherAlerts#/functions/RetrieveAlerts
method = 'GET'
href = '/alerts'

  # Query parameters
  [map.RetrieveAlerts.http.query]
  'addressLocality' = '@addressLocality'                                        # -> @ resolves to http://supermodel.io/superface/WeatherAlerts#/descriptors/RetrieveAlerts/descriptors/addressLocality
  'jinejParamter' = '42'

  [map.RetrieveAlerts.http.headers]
  'accept' = 'application/json'

  # Response mapping
  [map.RetrieveAlerts.http.response.200.'application/json'.body]
  '@title' = '.title'                                                           # -> @ resolves to http://supermodel.io/superface/WeatherAlerts#/descriptors/RetrieveAlerts/rt/title
  '@description' = '.description'
  '@severity' = '.severity'
  '@startDate' = '.startDate'
  '@endDate' = '.endDate'
  '@jinejParamter' = ':PEPA'

  # Error mapping
  [map.RetrieveAlerts.http.response.400.'application/problem+json'.body]
  '@http://supermodel.io/superface/WeatherAlerts#/models/Error/message' = '.message'


[map.RetrieveAlerts.graphql]
query = ' '