profile = 'n/a'

[provider]
id = 'n/a'

#
# Computation functions
#
[ops.Compute]
parameters = ['param1', 'param2']

  # https://formulajs.info/functions/
  [ops.Compute.eval]
    '.answer[0]' = 42
    '.answer[1]' = '$parameters.param1 + $parameters.param'
    '.answer[2]' = 'REGEXREPLACE("Sutoiku", "utoiku", "TOIC")'     
    '.answer[3]' = 'NOW()'
    '.answer[4]' = 'IF(true, "YES", "NO")'
    '.answer[5]' = '''
      IF($parameters.param1 > 0, 
        RATE(2*12, -1000, -10000, 100000, 0, 0.1), 
        BITLSHIFT(42, 24),
      )
      '''

#
# Conversion functions
#
[ops.ConvertToUSD]
parameters = ['eurValue']

  [ops.ConvertToUSD.http]
  method = 'GET'
  href = 'https://api.exchangeratesapi.io/latest?symbols=EUR,USD'

    [ops.ConvertToUSD.http.response.200.'application/json'.body]
    '.resultInUSD' = '$parameters.eurValue * .rates.USD'


#
# Multi-step functions
#
[[ops.Multistep.steps]]
run = 'Compute'
  [ops.Multistep.steps.result]
  '$euros' = '.answer[0]'        # Also `ops.Multistep.steps[0].result.answer[0]

[[ops.Multistep.steps]]
run = 'ConvertToUSD'
  [ops.Multistep.steps.parameters]
  eurValue = '$euros'
  [ops.Multistep.steps.result]
  'usdValue' = '.resultInUSD'  

