#
# Map for profile
#
profile = 'http://supermodel.io/superface/CRM/Customers'

#
# Curies
#
[curies.stream]
profile = 'http://supermodel.io/superface/superdriver/Stream'

#
# Provider details
#
[provider]
id = 'http://superface.ai/directory/hubspot'

#
# Affordance map
#
[map.RetrieveCustomers.http]
method = 'GET'
href = '/companies/v2/companies/paged'

  # Query parameters
  [map.RetrieveCustomers.http.query]
  offset = '@stream:offset'
  limit = '@stream:limit'
  properties = ['name', 'website']
  hapikey = '$security.apikey'

  # Response
  [map.RetrieveCustomers.http.response.200.'application/json'.body]
  '@customers/id' = '.companies[].companyId'
  '@customers/name' = '.companies[].properties.name.value'
  '@customers/website' = '.companies[].properties.website.value'
  '@customerCount' = '\=COUNT(.companies)'                                        # Decide: formula.js or jq?
  '@customerCountAlt' = '.companies | length'  
  
  # Streaming
  '@stream:offset' = '.offset'
  '@stream:hasMore' = '.has-more'
