# Context
profile = 'http://supermodel.io/superface/CRM/Customers'

# Curies
[curies.stream]
profile = 'http://supermodel.io/superface/superdriver/Page'

# Provider details
[provider]
id = 'http://superface.ai/directory/pipedrive'


# Affordance map

# Step 1: Check if filter exists
[[map.RetrieveCustomers.steps]]  
when = '@since'
run = 'FindFilter'

  [map.RetrieveCustomers.steps.parameters]
  filterName = 'superface-filter'

  [map.RetrieveCustomers.steps.result]
  '$filterId' = '.filterId'


# Step 2: Create filter if not
[[map.RetrieveCustomers.steps]]
when = '@since && !$filterId'                                                   # Alternative syntax: AND(@since, NOT($filterId)) - https://formulajs.info/functions/
run = 'CreateFilter'

  [map.RetrieveCustomers.steps.parameters]
  since = '@since'                                                              # -> resolves to http://supermodel.io/superface/CRM/Customers#/descriptors/RetrieveCustomers/descriptors/since

  [map.RetrieveCustomers.steps.result]
  '$filterId' = '.filterId'  
  
# Step 3: Retrieve organizations
[[map.RetrieveCustomers.steps]]
run = 'RetrieveOrganizations'

  [map.RetrieveCustomers.steps.parameters]      # available as $parameters inside the operation
  offset = '@stream:offset'
  limit = '@stream:limit'
  filterId = '$filterId'

  [map.RetrieveCustomers.steps.result]          # available as $result inside the operation
  '@customers' = '.customers'
  '@customersCount' = '.count'

# 
# Operations
#

# Add filter
[ops.AddFilter]
parameters = [ 'since' ]

[ops.AddFilter.http]
method = 'POST'
href = '/filters'

  [ops.AddFilter.http.query.api_token]
  api_token = '$security.apikey'

  # Crazy pipedrive API madness
  #   See https://pipedrive.readme.io/docs/adding-a-filter
  #   Note: This is actually not real pipedrive condition as that is very complex for this demo
  [ops.AddFilter.http.request.'application/json'.body]
  '.name' = 'a filter'          # hard-set value 'a filter'
  '.type' = 'organization'      # hard-set value 'organization'
  '.updatedAfter' = '$parameters.since'    # input step parameter using jq notation

  [ops.AddFilter.http.response.200.'application/json'.body]
  '.filterId' = '.id' # get the value of '.id' and store it in 'filterId' field


# RetrieveOrganizations
[ops.RetrieveOrganizations]
parameters = [ 'filterId', 'offset', 'limit' ]

[ops.RetrieveOrganizations.http]
method = 'GET'
href = '/organizations'

  # Query parameters
  [ops.RetrieveOrganizations.http.query]
  api_token = '$security.apikey'
  filter_id = '$parameters.filterId'
  start = '$parameters.offset'
  limit = '$parameters.limit'  

  # Map response to result structure
  [ops.RetrieveOrganizations.http.response.200.'application/json'.body]
  '.customers[].id' = '.data[].id'                                              # Also `.customers[].id` is short for `$result.customers[].id`
  '.customers[].name' = '.data[].name'
  '.count' = 'COUNT(.data)'       # formula.js syntax
  # '.customerCount' = '.data | COUNT'      # mixed formula.js and jq syntax
  # '.customerCount' = '.data | length'   # jq syntax
  

  '.offset' = '.additional_data.pagination.next_start'
  '.hasMore' = '.additional_data.pagination.more_items_in_collection'


# Right-hand values starting with:
# `:`         - literal value, example: `:value`
# `.`         - jq expression, example: `.expression`
# `$`         - variable `$variable`
# no prefix   - relative or absolute URL of a descriptor `descriptor`

# consider
# `$$`        - for global variables
# `@`         - for descrioptor identifiers