# Context
profile = 'http://supermodel.io/superface/telco/SendSMS'

# Provider
[provider]
id = 'http://superface.ai/directory/twilio'

# Mapping
[map.SendMessage.http]
method = 'GET'
href = '/2010-04-01/Accounts/{AccountSID}/Messages.json'

  # href variables
  [map.SendMessage.http.hrefVariables]
  AccountSID = '$security.basic.user'

  # Any http headers, if needed
  [map.SendMessage.http.request.headers]
  some-http-header = 42

  # Request body mapping
  [map.SendMessage.http.request.'application/x-www-form-urlencoded'.body]
  '.From' = '@from'                                                             # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/from
  '.To' = '@to'                                                                 # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/to
  '.Body' = '@message'                                                          # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/descriptors/message

  # Response body mapping
  #   values are using jq syntax - https://stedolan.github.io/jq, https://jqplay.org/#
  #     alternativelly we can consider JSON Pointer https://tools.ietf.org/html/rfc6901
  [map.SendMessage.http.response.200.'application/json'.body]
  '@to' = '.to'                                                                 # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/rt/to
  '@id' = '.sid'                                                                # -> resolves http://supermodel.io/superface/telco/SendSMS#/descriptors/SendMessage/rt/sid
