'$id' = 'http://supermodel.io/superface/CRM/Customers'
'$schema' = 'http://superschema.org/draft-01/schema#'

title = 'Customers'
description = 'Customers (Client) information within a customer relationship management system (CRM)'

#
# Retrieve Customers Descriptor
#
[descriptors.RetrieveCustomers]
title = 'Retrieve Customers'
description = '''
  Retrieves all client records from a CRM. 
  Optionally, retrieves clients created only since a specified date and time. 
  '''
type = 'safe'

  #
  # Descriptors
  #
  [descriptors.RetrieveCustomers.descriptors.since]
  description = 'Optional timestamp. When provided, only the clients created after (inclusive) this timestamp are returned.'
  type = 'semantic'
  examples = [ '2018-03-02T07:53:47Z', '2018-03-02']

  #
  # Resource Type
  #
  [descriptors.RetrieveCustomers.rt.customers]
  '$ref' = '#/models/Customer'

  [descriptors.RetrieveCustomers.rt.customerCount]
  type = 'semantic'

#
# Customer
#
[models.Customer]
type = 'semantic'

  [descriptors.Customer.id]
  type = 'semantic'

  [descriptors.Customer.name]
  type = 'semantic'

  [descriptors.Customer.website]
  type = 'semantic'
