'$id' = 'http://supermodel.io/superface/telco/SendSMS'
'$schema' = 'http://superschema.org/draft-01/schema#'

title = 'Send SMS'
description = 'Send short text messages. A service conforming to this profile will offer  the affordance to send a text message between two phone numbers.'

#
# Send Message Affordance
#
[usecase.SendMessage]
title = 'Send a short SMS'
type = 'unsafe'

  #
  # Descriptors
  #
  [usecase.SendMessage.descriptors.from]
  type = 'semantic'                                                             # <- introduce hard typing here 
  description = 'E.164 phone number of the sender. See <https://www.twilio.com/docs/glossary/what-e164> for details.'

  [usecase.SendMessage.descriptors.to]
  type = 'semantic'
  description = 'E.164 phone number of the receiver.'

  [usecase.SendMessage.descriptors.message]
  type = 'semantic'
  description = 'The body of the SMS message.'

  #
  # Resource Type
  #
  [usecase.SendMessage.rt.to]
  type = 'semantic'

  [usecase.SendMessage.rt.sid]
  type = 'semantic'
