'$id' = 'http://supermodel.io/superface/WeatherAlerts'
'$schema' = 'http://superschema.org/draft-01/schema#'

title = 'Weather Alerts Profile'

#
# Descriptors
#
[functions.RetrieveAlerts]
title = 'Retrieve Alerts'
description = 'Retrieves alert at given address locality'
type = 'safe'

  #
  # Nested descriptors a.k.a. parameters
  #
  [functions.RetrieveAlerts.parameters.addressLocality]                         # -> http://supermodel.io/superface/WeatherAlerts#/functions/RetrieveAlerts/parameters/addressLocality
  description = 'Address locality to retrieve the alerts for'
  type = 'semantic'

  #
  # Resource type a.k.a. response
  #
  [functions.RetrieveAlerts.response.title]
  description = 'A brief description of the alert'
  type = 'semantic'

  [functions.RetrieveAlerts.response.description]
  description = 'A detailed description of the alert'
  type = 'semantic'

  [functions.RetrieveAlerts.response.severity]
  description = '''
    The severity of the weather alert. Will take one of the following values:
    - `advisory` (an individual should be aware of potentially severe weather)
    - `watch` (an individual should prepare for potentially severe weather)
    - `warning` (an individual should take immediate action to protect themselves and others from potentially severe weather).
  '''
  type = 'semantic'

  [functions.RetrieveAlerts.response.startDate]
  description = 'A brief description of the alert'
  type = 'semantic'

  [functions.RetrieveAlerts.response.endDate]
  description = 'A brief description of the alert'
  type = 'semantic'

  [functions.RetrieveAlerts.Error]

[models.Error.message]
  description = 'Error message'
