operation foo {
  return {
    answer = 42
    hash = { a: 1, b: 2 }
  }
}

operation fooWithArgs {
  return if (args.success) {
    answer = 42
  }

  error if (!args.succes) {
    message = "I am supposed to fail"
  }
}

operation bar {

  fooWithArgs(success = `Muj string ${someVar}`, neco = 4+2 ) 
  myReturn = return
  myError = error

  return if (!error) {
    finalAnswer = "The final answer is " + return.answer
  }

  return if (error) {
    finalAnswer = "There was an error " + error.message
  }

  someOtherFoo()
  return if (error) {
    ...
  }
}

operation countArray {
  count = 0
  
  forEach(args.array) {
    count = count + 1
  }

  return {
    answer = 'this is the count: ' + count
  }

}

operation GitHubGists {
  http get "https://api.github.com/gists" {
    request {
      headers {
        accept = "application/vnd.github.v3+json"
      }
    }

    response 200 "application/json" {
      return {
        requestId = headers["X-GitHub-Request-Id"]
        numberOfResults = body.length()
        authors = body.map((gist) => { return gist.owner.login })
      }
    }
  }
}






operation funcMain {
  run funcA {
    ...
  }

  run funcB {
    ...
  }
}